### PR TITLE
aquifying

### PR DESCRIPTION
**Pull request by cantide5ga**
This change is [Reviewable](https://reviewable.io/reviews/aquicore/npm-project-template/1)

### CODE REVIEW

**Comment by cantide5ga** [comment]
@caitlin-henry , @tony-aq, @mikedon, @trevoristall, @msakauye , @spicybits 
Aquifying for our need.  Probably better to check out code in repo to get a holistic view.


In a moment I want to expand the `init` script to pull in the `commit-msg` hook.  I think we should have an `aq-common` or other to pull things like the hook from.  Or do we have something already?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1#-:-KenMYXk82afO1qy7tMC:ba2ru7m)*

**Comment by cantide5ga** [comment]
*[package.json, line 23 at r1](https://reviewable.io:443/reviews/aquicore/npm-project-template/1#-KenVrcOPvToB0uFZxJq:-KenVrcOPvToB0uFZxJr:b-xbwtim) ([raw file](https://github.com/aquicore/npm-project-template/blob/23e499977986e50229478ee1d3d1a5cc7123cf91/package.json#L23)):*
> ```JSON
>   },
>   "dependencies": {},
>   "devDependencies": {
> ```

The versioning lock-in might be a bit confusing; refer to the `install:latest` script to see how this gets stomped with the latest and greatest.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Comment by cantide5ga** [comment]
*[src/js/HelloWorld.ts, line 1 at r1](https://reviewable.io:443/reviews/aquicore/npm-project-template/1#-KenXJoN2h1K2buSUVZp:-KenXJoN2h1K2buSUVZq:bmhz8vj) ([raw file](https://github.com/aquicore/npm-project-template/blob/23e499977986e50229478ee1d3d1a5cc7123cf91/src/js/HelloWorld.ts#L1)):*
> ```XML
> class HelloWord {
> ```

This is so git will push the folder structure but to also spark a conversation about test organization and naming.  My suggestions:
* __tests__ folder (a convention from Jest)
* specifying unit vs int vs functional; respectively HelloWorld.unit.spec.ts, HelloWorld.int.spec.ts, HelloWorld.func.spec.ts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Comment by cantide5ga** [comment]
*[src/js/HelloWorld.ts, line 1 at r1](https://reviewable.io:443/reviews/aquicore/npm-project-template/1#-KenXJoN2h1K2buSUVZp:-KenYgCI9meU2ibKWruI:bectohh) ([raw file](https://github.com/aquicore/npm-project-template/blob/23e499977986e50229478ee1d3d1a5cc7123cf91/src/js/HelloWorld.ts#L1)):*
<details><summary><i>Previously, cantide5ga (Michael Payne) wrote…</i></summary><blockquote>

This is so git will push the folder structure but to also spark a conversation about test organization and naming.  My suggestions:
* __tests__ folder (a convention from Jest)
* specifying unit vs int vs functional; respectively HelloWorld.unit.spec.ts, HelloWorld.int.spec.ts, HelloWorld.func.spec.ts
</blockquote></details>

*tests* should be \__tests__\

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Comment by cantide5ga** [comment]
*[src/js/HelloWorld.ts, line 1 at r1](https://reviewable.io:443/reviews/aquicore/npm-project-template/1#-KenXJoN2h1K2buSUVZp:-KenYr1ZdyZjCmcZEU56:brv1jjy) ([raw file](https://github.com/aquicore/npm-project-template/blob/23e499977986e50229478ee1d3d1a5cc7123cf91/src/js/HelloWorld.ts#L1)):*
<details><summary><i>Previously, cantide5ga (Michael Payne) wrote…</i></summary><blockquote>

*tests* should be \__tests__\
</blockquote></details>

Holy shit the formatting - should read \_\_tests\_\_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Comment by trevor-atlas** [comment]
Reviewed 1 of 5 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Comment by cantide5ga** [comment]
*[a discussion](https://reviewable.io:443/reviews/aquicore/npm-project-template/1#-KeoUfC5pTYOmiXfjVSx:-KeoUfC5pTYOmiXfjVSy:b3p9ehg) (no related file):*
One more thing to do is after this is a go, I'll need to mirror this fork so we can make this private.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Comment by mikedon** [comment]
Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Comment by mikedon** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 28 at r2](https://reviewable.io:443/reviews/aquicore/npm-project-template/1#-Kf-Agrt6eE9oj3jkWrx:-Kf-Agrt6eE9oj3jkWry:b-xh083k) ([raw file](https://github.com/aquicore/npm-project-template/blob/6dba76a0eb63176f1fd1b7c49bf71f32af60b6d5/package.json#L28)):*
> ```JSON
>     "tslint": "^4.5.1",
>     "typescript": "^1.6.2",
>     "typings": "^0.8.1"
> ```

can we just use npm for type defintions?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/aquicore/npm-project-template/1)*

**Pull request merged**
